"DOTAAbilities"
{
  "ability_base_datadriven" {
    // General
    //-------------------------------------------------------------------------------------------------------------
    "BaseClass"       "   "
    "AbilityType"         "DOTA_ABILITY_TYPE_BASIC"
    "AbilityBehavior"       "DOTA_ABILITY_BEHAVIOR_NONE"
    "OnCastbar"           "1"
    "OnLearnbar"          "1"
    "FightRecapLevel"       "0"
    "AbilityTextureName"      "ability_base" // test comment

    // Stats
    //-------------------------------------------------------------------------------------------------------------
    "AbilityCastRange"        "0"
    "AbilityCastRangeBuffer"    "250"
    "AbilityCastPoint"        "0.0 0.0 0.0 0.0"
    "AbilityChannelTime"      "0.0 0.0 0.0 0.0"
    "AbilityCooldown"       "0.0 0.0 0.0 0.0"
    "AbilityDuration"       "0.0 0.0 0.0 0.0"
    "AbilitySharedCooldown"     ""
    "AbilityDamage"         "0 0 0 0"
    "AbilityManaCost"       "0 0 0 0"
    "AbilityModifierSupportValue" "1.0" // for stats tracking.
    "AbilityModifierSupportBonus" "0"   // for stats tracking.

    // Item Info
    //-------------------------------------------------------------------------------------------------------------
    "ItemCost"            "0"
    "ItemInitialCharges"      "0"
    "ItemCombinable"        "1"
    "ItemPermanent"         "1"
    "ItemStackable"         "0"
    "ItemRecipe"          "0"
    "ItemDroppable"         "1"
    "ItemPurchasable"       "1"
    "ItemSellable"          "1"
    "ItemRequiresCharges"     "0"
    "ItemKillable"          "1"
    "ItemDisassemblable"      "0"
    "ItemShareability"        "ITEM_NOT_SHAREABLE"
    "ItemDeclaresPurchase"      "0"
  }


  //=================================================================================================================
  // Recipe: Abyssal Blade
  //=================================================================================================================
  "item_recipe_abyssal_blade"
  {
    "ID"            "207"   // unique ID "quotes"
    "ItemCost"          "1550"
    "ItemShopTags"          ""
    "ItemRecipe"          "1"
    "ItemResult"          "item_abyssal_blade"
    "ItemRequirements" { // comment on header after curly
      "01"            "item_basher;item_vanguard"
    }
    "AbilitySpecial" // comment on header
    {
      "01"
      {
        "var_type"                                        "FIELD_FLOAT" // other test
        "hero_duration"                                   "1.0 1.0 1.0 1.0"
      }
    }
    "AbilityValues"
    {
      "bonus_damage"                                      "15 20 30 45 65"
      "kv_block"
      {
        "key1"                                             "A B C D"
        "key2"                                             "E F G H"
      }
      // kv block without "kv_block"
      {
        "key1"                                             "lala"
        "key4"                                             "123"
      }
    }
  }

  //=================================================================================================================
  // Recipe: Test item with bad indentation and text outside of quotes
  //=================================================================================================================
  "item_recipe_test_item"
  {
    "ID"            "1000000"   // unique ID "quotes"
    "ItemCost"          "1550"
    "ItemShopTags"          ""
    "ItemRecipe"          "1" I am supposed to be a comment but I forgot these / /
    "ItemResult"          "item_test_item"
    "ItemRequirements" { // comment on header after curly
      "01"            "item_something;item_thing"
    }
    "AbilitySpecial" // comment on header
    { "05"
      { "var_type"                                        "FIELD_INTEGER"
        "duration"                                   "1 2 3 4"
      }  }
    "another_kv_block" {
        "key1"                                             "shazam"
        "key2"                                             "alakhazam"
      }    }

}
