"DOTAAbilities"
{
  "ability_base_datadriven" {
    // General
    //-------------------------------------------------------------------------------------------------------------
    "BaseClass"       "   "
    "AbilityType"         "DOTA_ABILITY_TYPE_BASIC"
    "AbilityBehavior"       "DOTA_ABILITY_BEHAVIOR_NONE"
    "OnCastbar"           "1"
    "OnLearnbar"          "1"
    "FightRecapLevel"       "0"
    "AbilityTextureName"      "ability_base" // test comment

    // Stats
    //-------------------------------------------------------------------------------------------------------------
    "AbilityCastRange"        "0"
    "AbilityCastRangeBuffer"    "250"
    "AbilityCastPoint"        "0.0 0.0 0.0 0.0"
    "AbilityChannelTime"      "0.0 0.0 0.0 0.0"
    "AbilityCooldown"       "0.0 0.0 0.0 0.0"
    "AbilityDuration"       "0.0 0.0 0.0 0.0"
    "AbilitySharedCooldown"     ""
    "AbilityDamage"         "0 0 0 0"
    "AbilityManaCost"       "0 0 0 0"
    "AbilityModifierSupportValue" "1.0" // for stats tracking.
    "AbilityModifierSupportBonus" "0"   // for stats tracking.

    // Item Info
    //-------------------------------------------------------------------------------------------------------------
    "ItemCost"            "0"
    "ItemInitialCharges"      "0"
    "ItemCombinable"        "1"
    "ItemPermanent"         "1"
    "ItemStackable"         "0"
    "ItemRecipe"          "0"
    "ItemDroppable"         "1"
    "ItemPurchasable"       "1"
    "ItemSellable"          "1"
    "ItemRequiresCharges"     "0"
    "ItemKillable"          "1"
    "ItemDisassemblable"      "0"
    "ItemShareability"        "ITEM_NOT_SHAREABLE"
    "ItemDeclaresPurchase"      "0"
  }


  //=================================================================================================================
  // Recipe: Abyssal Blade
  //=================================================================================================================
  "item_recipe_abyssal_blade"
  {
    "ID"            "207"   // unique ID "quotes"
    "ItemCost"          "1550"
    "ItemShopTags"          ""
    "ItemRecipe"          "1"
    "ItemResult"          "item_abyssal_blade"
    "ItemRequirements" { // comment on header after curly
      "01"            "item_basher;item_vanguard"
    }
    "AbilitySpecial" // comment on header
    {
      "01"
      {
        "var_type"                                        "FIELD_FLOAT" // other test
        "hero_duration"                                   "1.0 1.0 1.0 1.0"
      }
    }
    "AbilityValues"
    {
      "bonus_damage"                                      "15 20 30 45 65"
      "kv_block"
      {
        "key1"                                             "A B C D"
        "key2"                                             "E F G H"
      }
      // kv block without "kv_block"
      {
        "key1"                                             "lala"
        "key4"                                             "123"
      }
    }
  }

  //=================================================================================================================
  // Recipe: Test item with bad indentation and text outside of quotes
  //=================================================================================================================
  "item_recipe_test_item"
  {
    "ID"            "1000000"   // unique ID "quotes"
    "ItemCost"          "1550"
    "ItemShopTags"          ""
    "ItemRecipe"          "1" I am supposed to be a comment but I forgot these / /
    "ItemResult"          "item_test_item"
    "ItemRequirements" { // comment on header after curly
      "01"            "item_something;item_thing"
    }
    "AbilitySpecial" // comment on header
    { "05"
      { "var_type"                                        "FIELD_INTEGER"
        "duration"                                   "1 2 3 4"
      }  }
    "another_kv_block" {
        "key1"                                             "shazam"
        "key2"                                             "alakhazam"
      }    }

  //=================================================================================================================
  // Recipe: Aeon Disk 1
  //=================================================================================================================
  "item_recipe_aeon_disk_oaa"
  {
    // General
    //-------------------------------------------------------------------------------------------------------------
    "ID"                                                  "80255"
    "BaseClass"                                           "item_datadriven"
    "Model"                                               "models/props_gameplay/recipe.vmdl"
    "AbilityTextureName"                                  "custom/recipe/recipe_1"

    // Item Info
    //-------------------------------------------------------------------------------------------------------------
    "ItemCorePointCost"                                   "0"
    "ItemCost"                                            "1200"
    "ItemShopTags"                                        ""

    // Recipe
    //-------------------------------------------------------------------------------------------------------------
    "ItemRecipe"                                          "1"
    "ItemResult"                                          "item_aeon_disk_oaa"
    "ItemRequirements"
    {
      "01"                                                "item_vitality_booster;item_energy_booster"
    }
  }

  //=================================================================================================================
  // Aeon Disk 1
  //=================================================================================================================
  "item_aeon_disk_oaa"
  {
    // General
    //-------------------------------------------------------------------------------------------------------------
    "ID"                                                  "80256"
    "BaseClass"                                           "item_lua"
    "ScriptFile"                                          "items/aeon_disk.lua"
    "AbilityBehavior"                                     "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    "AbilityTextureName"                                  "custom/combo_breaker"

    // Stats
    //-------------------------------------------------------------------------------------------------------------
    "AbilityCooldown"                                     "105 95 85 75 65" // OAA old: "105 95 75 55 35"
    "AbilitySharedCooldown"                               "combobreaker"
    "AbilityManaCost"                                     "0"

    // Spicy Parameters
    //-------------------------------------------------------------------------------------------------------------
    "MaxUpgradeLevel"                                     "5"
    "ItemBaseLevel"                                       "1"
    "UpgradesItems"                                       "item_aeon_disk_oaa;item_aeon_disk_2;item_aeon_disk_3;item_aeon_disk_4;item_aeon_disk_5"

    // Item Info
    //-------------------------------------------------------------------------------------------------------------
    "ItemCost"                                            "3000"
    "ItemShopTags"                                        "health_pool;mana_pool"
    "ItemQuality"                                         "epic"
    "ItemAliases"                                         "ad;aeon disk"
    "ItemDeclarations"                                    "DECLARE_PURCHASES_IN_SPEECH | DECLARE_PURCHASES_TO_SPECTATORS"

    // Special
    //-------------------------------------------------------------------------------------------------------------
    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                                        "FIELD_INTEGER"
        "bonus_health"                                    "250 500 1000 1750 2750"
      }
      "02"
      {
        "var_type"                                        "FIELD_INTEGER"
        "bonus_mana"                                      "300 400 550 750 1000"
      }
      "03"
      {
        "var_type"                                        "FIELD_INTEGER"
        "health_threshold_pct"                            "70"
      }
      "04"
      {
        "var_type"                                        "FIELD_INTEGER"
        "status_resistance"                               "75"
      }
      "05"
      {
        "var_type"                                        "FIELD_FLOAT"
        "buff_duration"                                   "2.5"
      }
      "06"
      {
        "var_type"                                        "FIELD_INTEGER"
        "cooldown_tooltip"                                "105 95 85 75 65"
      }
    }
  }

}
